theme: minima
title: Life of Smita
author: Smita Rosemary
email: srosemary@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 HI!This is a few small things about me that I'd like to share!
 Go ahead and check out my socials!!

# social links
twitter_username: RosemarySmita # DO NOT include the @ character, or else the build will fail!
github_username:  smithsrose # DO NOT include the @ character, or else the build will fail!
instagram_username: smiths_rose

show_excerpts: true # set to false to remove excerpts on the homepage
